/**
 * @file can_gopher.h
 *
 * @brief This header file was generated by cantools version 40.2.1 Mon May  5 20:30:00 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#ifndef CAN_GOPHER_H
#define CAN_GOPHER_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

#ifndef EINVAL
#    define EINVAL 22
#endif

/* Frame ids. */
#define CAN_GOPHER_STATE_FRAME_ID (0x101u)
#define CAN_GOPHER_COMMAND_A_FRAME_ID (0x201u)

/* Frame lengths in bytes. */
#define CAN_GOPHER_STATE_LENGTH (1u)
#define CAN_GOPHER_COMMAND_A_LENGTH (8u)

/* Extended or standard frame types. */
#define CAN_GOPHER_STATE_IS_EXTENDED (0)
#define CAN_GOPHER_COMMAND_A_IS_EXTENDED (0)

/* Frame cycle times in milliseconds. */


/* Signal choices. */


/* Frame Names. */
#define CAN_GOPHER_STATE_NAME "state"
#define CAN_GOPHER_COMMAND_A_NAME "command_a"

/* Signal Names. */
#define CAN_GOPHER_STATE_SYSTEM_STATE_NAME "system_state"
#define CAN_GOPHER_COMMAND_A_COMMAND_U16_0_NAME "command_u16_0"
#define CAN_GOPHER_COMMAND_A_COMMAND_U16_1_NAME "command_u16_1"
#define CAN_GOPHER_COMMAND_A_COMMAND_U16_2_NAME "command_u16_2"
#define CAN_GOPHER_COMMAND_A_COMMAND_U16_3_NAME "command_u16_3"

/**
 * Signals in message state.
 *
 * State machine info
 *
 * All signal values are as on the CAN bus.
 */
struct can_gopher_state_t {
    /**
     * Range: 0..255 (0..255 -)
     * Scale: 1
     * Offset: 0
     */
    uint8_t system_state;
};

/**
 * Signals in message command_a.
 *
 * All signal values are as on the CAN bus.
 */
struct can_gopher_command_a_t {
    /**
     * Range: 0..65535 (0..65535 unit)
     * Scale: 1
     * Offset: 0
     */
    uint16_t command_u16_0;

    /**
     * Range: 0..65535 (0..65535 unit)
     * Scale: 1
     * Offset: 0
     */
    uint16_t command_u16_1;

    /**
     * Range: 0..65535 (0..65535 unit)
     * Scale: 1
     * Offset: 0
     */
    uint16_t command_u16_2;

    /**
     * Range: 0..65535 (0..65535 unit)
     * Scale: 1
     * Offset: 0
     */
    uint16_t command_u16_3;
};

/**
 * Pack message state.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_gopher_state_pack(
    uint8_t *dst_p,
    const struct can_gopher_state_t *src_p,
    size_t size);

/**
 * Unpack message state.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_gopher_state_unpack(
    struct can_gopher_state_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from state.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_gopher_state_init(struct can_gopher_state_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint8_t can_gopher_state_system_state_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float can_gopher_state_system_state_decode(uint8_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_gopher_state_system_state_is_in_range(uint8_t value);

/**
 * Pack message command_a.
 *
 * @param[out] dst_p Buffer to pack the message into.
 * @param[in] src_p Data to pack.
 * @param[in] size Size of dst_p.
 *
 * @return Size of packed data, or negative error code.
 */
int can_gopher_command_a_pack(
    uint8_t *dst_p,
    const struct can_gopher_command_a_t *src_p,
    size_t size);

/**
 * Unpack message command_a.
 *
 * @param[out] dst_p Object to unpack the message into.
 * @param[in] src_p Message to unpack.
 * @param[in] size Size of src_p.
 *
 * @return zero(0) or negative error code.
 */
int can_gopher_command_a_unpack(
    struct can_gopher_command_a_t *dst_p,
    const uint8_t *src_p,
    size_t size);

/**
 * Init message fields to default values from command_a.
 *
 * @param[in] msg_p Message to init.
 *
 * @return zero(0) on success or (-1) in case of nullptr argument.
 */
int can_gopher_command_a_init(struct can_gopher_command_a_t *msg_p);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_gopher_command_a_command_u16_0_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float can_gopher_command_a_command_u16_0_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_gopher_command_a_command_u16_0_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_gopher_command_a_command_u16_1_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float can_gopher_command_a_command_u16_1_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_gopher_command_a_command_u16_1_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_gopher_command_a_command_u16_2_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float can_gopher_command_a_command_u16_2_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_gopher_command_a_command_u16_2_is_in_range(uint16_t value);

/**
 * Encode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to encode.
 *
 * @return Encoded signal.
 */
uint16_t can_gopher_command_a_command_u16_3_encode(float value);

/**
 * Decode given signal by applying scaling and offset.
 *
 * @param[in] value Signal to decode.
 *
 * @return Decoded signal.
 */
float can_gopher_command_a_command_u16_3_decode(uint16_t value);

/**
 * Check that given signal is in allowed range.
 *
 * @param[in] value Signal to check.
 *
 * @return true if in range, false otherwise.
 */
bool can_gopher_command_a_command_u16_3_is_in_range(uint16_t value);


#ifdef __cplusplus
}
#endif

#endif
