/**
 * @file can_gopher.c
 *
 * @brief This source file was generated by cantools version 40.2.1 Mon May  5 20:30:00 2025.
 *
 * @copyright Copyright (c) 2018-2019 Erik Moqvist
 *
 * @par License
 * The MIT License (MIT)
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include <string.h>

#include "can_gopher.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u16(
    uint16_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint16_t unpack_left_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint16_t unpack_right_shift_u16(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint16_t)((uint16_t)(value & mask) >> shift);
}

int can_gopher_state_pack(
    uint8_t *dst_p,
    const struct can_gopher_state_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 1);

    dst_p[0] |= pack_left_shift_u8(src_p->system_state, 0u, 0xffu);

    return (1);
}

int can_gopher_state_unpack(
    struct can_gopher_state_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 1u) {
        return (-EINVAL);
    }

    dst_p->system_state = unpack_right_shift_u8(src_p[0], 0u, 0xffu);

    return (0);
}

int can_gopher_state_init(struct can_gopher_state_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_gopher_state_t));

    return 0;
}

uint8_t can_gopher_state_system_state_encode(float value)
{
    return (uint8_t)(value);
}

float can_gopher_state_system_state_decode(uint8_t value)
{
    return ((float)value);
}

bool can_gopher_state_system_state_is_in_range(uint8_t value)
{
    (void)value;

    return (true);
}

int can_gopher_command_a_pack(
    uint8_t *dst_p,
    const struct can_gopher_command_a_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u16(src_p->command_u16_0, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u16(src_p->command_u16_0, 8u, 0xffu);
    dst_p[2] |= pack_left_shift_u16(src_p->command_u16_1, 0u, 0xffu);
    dst_p[3] |= pack_right_shift_u16(src_p->command_u16_1, 8u, 0xffu);
    dst_p[4] |= pack_left_shift_u16(src_p->command_u16_2, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u16(src_p->command_u16_2, 8u, 0xffu);
    dst_p[6] |= pack_left_shift_u16(src_p->command_u16_3, 0u, 0xffu);
    dst_p[7] |= pack_right_shift_u16(src_p->command_u16_3, 8u, 0xffu);

    return (8);
}

int can_gopher_command_a_unpack(
    struct can_gopher_command_a_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->command_u16_0 = unpack_right_shift_u16(src_p[0], 0u, 0xffu);
    dst_p->command_u16_0 |= unpack_left_shift_u16(src_p[1], 8u, 0xffu);
    dst_p->command_u16_1 = unpack_right_shift_u16(src_p[2], 0u, 0xffu);
    dst_p->command_u16_1 |= unpack_left_shift_u16(src_p[3], 8u, 0xffu);
    dst_p->command_u16_2 = unpack_right_shift_u16(src_p[4], 0u, 0xffu);
    dst_p->command_u16_2 |= unpack_left_shift_u16(src_p[5], 8u, 0xffu);
    dst_p->command_u16_3 = unpack_right_shift_u16(src_p[6], 0u, 0xffu);
    dst_p->command_u16_3 |= unpack_left_shift_u16(src_p[7], 8u, 0xffu);

    return (0);
}

int can_gopher_command_a_init(struct can_gopher_command_a_t *msg_p)
{
    if (msg_p == NULL) return -1;

    memset(msg_p, 0, sizeof(struct can_gopher_command_a_t));

    return 0;
}

uint16_t can_gopher_command_a_command_u16_0_encode(float value)
{
    return (uint16_t)(value);
}

float can_gopher_command_a_command_u16_0_decode(uint16_t value)
{
    return ((float)value);
}

bool can_gopher_command_a_command_u16_0_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_gopher_command_a_command_u16_1_encode(float value)
{
    return (uint16_t)(value);
}

float can_gopher_command_a_command_u16_1_decode(uint16_t value)
{
    return ((float)value);
}

bool can_gopher_command_a_command_u16_1_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_gopher_command_a_command_u16_2_encode(float value)
{
    return (uint16_t)(value);
}

float can_gopher_command_a_command_u16_2_decode(uint16_t value)
{
    return ((float)value);
}

bool can_gopher_command_a_command_u16_2_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}

uint16_t can_gopher_command_a_command_u16_3_encode(float value)
{
    return (uint16_t)(value);
}

float can_gopher_command_a_command_u16_3_decode(uint16_t value)
{
    return ((float)value);
}

bool can_gopher_command_a_command_u16_3_is_in_range(uint16_t value)
{
    (void)value;

    return (true);
}
